nspcc-dev/neofs-api-go

go.mod
service/verify.go
service/verify_test.go

```
// Before
BenchmarkSignRequestHeader-8   	     146	   8070375 ns/op	 4210607 B/op	      48 allocs/op
BenchmarkVerifyRequestHeader-8   	      14	  83058325 ns/op	42085955 B/op	    1601 allocs/op
// After
BenchmarkSignRequestHeader-8   	     156	   7709172 ns/op	   33902 B/op	      45 allocs/op
BenchmarkVerifyRequestHeader-8   	      15	  76910232 ns/op	   54368 B/op	    1563 allocs/op
// Summary:
benchmark                          old ns/op     new ns/op     delta
BenchmarkSignRequestHeader-8       8070375       7709172       -4.48%
BenchmarkVerifyRequestHeader-8     83058325      76910232      -7.40%
benchmark                          old allocs     new allocs     delta
BenchmarkSignRequestHeader-8       48             45             -6.25%
BenchmarkVerifyRequestHeader-8     1601 …
```

service: Use sync pool for Sign/Verify request headers

---

session/service.go
session/store.go
session/store_test.go

Private token based on the token with private key. Therefore
it must inherit public key field through constructor parameter.

session: Add public key to the constructor of new private token

---

go.mod
go.sum

New version of neofs-crypto library fixes bug
with `SignRFC6979()` function. This function
used in accounting library to sign withdraw cheque.

dep: Update neofs-crypto library to v0.3.0

---

object/service.go
object/service_test.go
object/types.go

`BasicACL` have set of rules for every request type. ACL will be processed before any request specific handlers. Therefore we need to determine request type in generic `Request` interface, which is used in pre-processors of object service implementation.
For now `requestType` is a private type in object service implementation.

object: Add request type and `Type` function in `Request` interface

---

session/private.go
session/private_test.go
session/store.go
session/store_test.go
session/types.go

All sessions in NeoFS has limited in epochs lifetime. There is a need
to limit the lifetime of private session tokens.
This commmit:
* extends PrivateToken interface with Expired method;
* defines EpochLifetimeStore interface with RemoveExpired method
and embeds it to PrivateTokenStore interface;
* adds epoch value parameter to private token constructor.

session: support the expiration of private tokens

---

session/private.go
session/private_test.go
session/store.go
session/store_test.go
session/types.go

In previous implementation PrivateTokenStore was not stored an OwnerID of the session. It is necessary to store the identifier of the owner of the token to verify ownership.

session: add OwnerID to a private token storage key

---

object/types.go
object/types_test.go

Fixes `proto: don't know how to copy` message.

object: add Token header case to CopyTo

---

accounting/sign.go
accounting/sign_test.go
accounting/types.go
accounting/types_test.go
bootstrap/sign.go
bootstrap/sign_test.go
bootstrap/types.go
bootstrap/types_test.go
container/sign.go
container/sign_test.go
container/types.go
container/types_test.go
object/sign.go
service/errors.go
service/role.go
service/token.go
service/utils.go
service/utils_test.go
session/request.go
state/sign.go
state/sign_test.go
state/types.go
state/types_test.go

In order to support the signing through `service.AddSignatureWithKey`, `service.SignDataWithSessionToken` and verification through the related functions, all request messages must implement `service.SignedDataSource` interface methods.

Implement SignedDataSource on all request messages

---

service/token.go
service/token_test.go

After presented changes:
- any `SessionToken` instance can be signed/verified via `AddSignatureWithKey`/`VerifySignatureWithKey` and doesn't need to implement additional methods;
- the token signature is based on the values of the token parameters and is independent of implementation.

service: implement SessionToken wrapper for Sign/Verify support

---

service/token.go
service/token_test.go

Summary:
- remove the owner key from the signed payload of `SessionToken`;
- call `OwnerKey` field setter in `AddSignKey` method of signed session token.

Change AddSignKey of SessionToken

---

session/errors.go
session/private.go
session/private_test.go
session/types.go

Summary:
- replace `PublicKey` and `SIgnData` methods with `PrivateKey` one;
- implement function over `PrivateToken` for public key bytes receiving.

session: refactor PrivateToken interface

---

accounting/sign_test.go
bootstrap/sign_test.go
container/sign_test.go
object/sign_test.go
service/errors.go
service/sign.go
service/sign_test.go
service/types.go
service/verify_test.go
session/create.go
session/create_test.go
state/sign_test.go

In previous implementation service package provided types and functions
that wrapped signing/verification of data with session token.
This allowed us to use these functions for signing / verification of
service requests of other packages. To support the expansion of messages
with additional parts that need to be signed, you must be able to easily
expand the signed data with new parts.
To achieve the described goal, this commit makes the following changes:
* adds GroupSignedPayloads and GroupVerifyPayloads functions;
* renames SignedDataWithToken to RequestData, DataWithTokenSignAccumulator
to RequestSignedData, DataWithTokenSignSource to RequestVerifyData;
* renames SignDataWithSessionToken/VerifyAccumulatedSignaturesWithToken
function to SignRequestData/VerifyRequestData and makes it to …

service: support broken apart signable payload of the requests

---

service/bearer.go
service/bearer_test.go
service/sign_test.go
service/verify.go
service/verify_test.go

This commit:
* implements (Set)ExpirationEpoch methods on BearerTokenMsg;
* removes BearerTokenMsg wrapper.

service: implement BearerToken interface on BearerTokenMsg message

---

service/sign.go
service/sign_test.go
service/types.go
service/verify.go

This commit changes SignRequestData / VerifyRequestData functions to
add the list of previous public keys to a signed message for all
requests.

service: sign requests on the principle of Matryoshka

---

v2/accounting/accounting.go
v2/accounting/convert.go
v2/service/convert.go
v2/service/service.go
v2/signature/sign.go

Adds uni-structures with gRPC converters for:
- `service.BearerToken`;
- `service.ResponseMetaHeader`, `service.ResponseVerificationHeader`;
- `accounting.BalancerResponse`.

Implement some universal structures

---

v2/accounting/client.go
v2/accounting/test/client_test.go
v2/container/client.go
v2/container/test/client_test.go
v2/object/client.go
v2/object/test/client_test.go
v2/session/client.go
v2/session/test/client_test.go

Client constructor `New` will be used as `package.New()` in external packages. This definition is not very clear since it can create new structure or new client or whatever. `package.NewClient()` is quite unambiguous.

Rename unified client constructors

---

pkg/object/address.go
pkg/object/object.go
v2/object/marshal.go
v2/object/marshal_test.go
v2/refs/marshal.go
v2/refs/marshal_test.go

- Implement stable unmarshalers on v2 `refs.Address` and `object.Object`;
- Add  `Address` type to object SDK;
- Implement some useful methods and functions in object SDK.

Implement methods for use in local storage

---

pkg/object/object.go
pkg/object/raw.go
pkg/object/rw.go

- fix constructors (`New`, `NewRaw`) and setters so that there are no unnecessary initializations of nested structures;
- remove no longer used `initObjectRecursive` function.
- add object deserialization function `FromBytes`.

sdk/object: Make some fixes and features

---

pkg/client/object.go
pkg/object/range.go
pkg/object/range_test.go

Define Range type in object package. Replace Range in client package with
the new one.

sdk: Define object range in object pkg

---

pkg/client/object.go

There is a issue when user sends payload chunk to the neofs node, but node closes connection earlier, e.g. node can return error as soon as it checked ACL permission and denied request.
In this case client will receive EOF error and it produces `could not send payload bytes to Put object stream` error, but in fact there is different error.
If we ignore EOF there then `stream.CloseAndRecv()` return correct error message later.

Ignore EOF on buffer copy in object.Put

---

pkg/client/netmap.go
pkg/client/opts.go

This PR adds support of netmap service in SDK client. NeoFS node will support netmap service after https://github.com/nspcc-dev/neofs-node/pull/84
This method can be used as a health checker to see if remote node is alive and responses to requests (cc: @im-kulikov)

Add endpoint info getter

---

pkg/client/object.go
pkg/token/session.go

In some cases SDK Client provided with signed and prepared session token. In this case we don't need to change verb or sign it.

Do not resign session token

---

pkg/netmap/selector.go
pkg/netmap/selector_test.go

When selector attribute is node provided it is
silently replaced by transparent ID, so that each node
resides in a separate bucket.
Close #174.

[#174] netmap: process unspecified attribute as ID

---

v2/acl/json.go
v2/container/json.go
v2/netmap/json.go

This way zero-values will not be omitted in resulting string.
```json
"version": {
"major": 2,
"minor": 0
},
```

v2: Print default values in JSON

---

pkg/token/bearer.go
pkg/token/bearer_test.go

Now `OwnerID` field is not required to be set. According to latest neofs-api specification, this field set if token was issued for specific owner. If this field is not set, then any user can use this token while it is correctly signed and has valid lifetime.
Lifetime is also can be omitted since node interpret empty lifetime as a lifetime with zero values.

sdk/client: Ease bearer token sanity check

---

pkg/client/accounting.go
pkg/client/client.go
pkg/client/container.go
pkg/client/netmap.go
pkg/client/object.go
pkg/client/opts.go
pkg/client/session.go

Attach tokens to SDK client

---

v2/acl/json.go
v2/acl/json_test.go
v2/container/json.go
v2/container/json_test.go
v2/netmap/json.go
v2/netmap/json_test.go

There is a proposal from @im-kulikov to return errors in JSON converters because these converters work with raw `[]byte` and error nil check is more clear for go-developers in case of data marshaling.

Return errors in JSON converters

---

pkg/client/client_test.go
pkg/client/netmap.go
pkg/container/container.go
pkg/netmap/clause.go
pkg/netmap/clause_test.go
pkg/netmap/context.go
pkg/netmap/filter.go
pkg/netmap/filter_test.go
pkg/netmap/helper_test.go
pkg/netmap/netmap.go
pkg/netmap/node_info.go
pkg/netmap/node_info_test.go
pkg/netmap/operation.go
pkg/netmap/operation_test.go
pkg/netmap/policy.go
pkg/netmap/policy_test.go
pkg/netmap/replica.go
pkg/netmap/replica_test.go
pkg/netmap/selector.go
pkg/netmap/selector_test.go

Replace type aliases to v2 types with full-fledged v2-compatible implementation.

sdk/netmap: Refactor types

---

pkg/client/object.go

According to API object.Head response contains signature of object ID rather than signature of object header itself.

Fix signature check in object header getter

---

pkg/client/accounting.go
pkg/client/container.go
pkg/client/netmap.go
pkg/client/object.go
pkg/client/opts.go
pkg/client/session.go
v2/client/options.go

Support dial timeout option in clients

---

pkg/client/container.go

Extended ACL tables should be signed with RFC-6979 standard. Fix `Client.GetEACL` implementation to verify eACL signature with `SignRFC6979` option.
Additionally implemented `Client.GetEACLWithSignatureMethod` that returns eACL with signature w/o the verification.

sdk/client: Fix signature verification in GetEACL method

---

pkg/object/splitid.go
pkg/object/splitid_test.go

SplitID is not set on non-split and virtual objects, so we should support this state in library.

Support nil value in SplitID

---

pkg/netmap/netmap.go
pkg/netmap/selector.go
pkg/netmap/selector_test.go

Use CBF=1 when strict policy can't be satisfied.
Close #156, #157.
Related #213, #214 . Need testing for sure.
Added test for #215.

[#157] netmap: Fallback to using minimal backup factor

---

pkg/netmap/netmap.go
pkg/netmap/selector_test.go

For `REP X` select X nodes from the default filter
and fail if it cannot be done.
Close #220.

[#220] netmap: process `REP X` policies correctly

---

pkg/client/container.go
pkg/container/id.go

client: Add function to get container structure and verify it

---

pkg/client/container.go
pkg/container/container.go
pkg/container/container_test.go
pkg/container/fmt.go
pkg/container/fmt_test.go

- implement getter and setter of container nonce which works with UUID type;
- implement constructor of pkg/container.Container which preliminary verifies message format.
Closes #194.

Verify container nonce format (UUID)

---

README.md

We don't have `go` workflow in the repository.

Fix badge in README file

---

pkg/netmap/context.go
pkg/netmap/netmap.go
pkg/netmap/selector.go
pkg/netmap/selector_test.go

Related to https://github.com/nspcc-dev/neofs-node/issues/347
If CBF value is not set, then netmap package uses default CBF value. However it modifies placement policy structure in `GetContainerNodes()` because policy passed as a pointer.
Instead package can store CBF value in internal context and use it without policy modification.

pkg/netmap: Add CBF field in placement context

---

pkg/container/announcement.go
pkg/container/announcement_test.go
v2/container/marshal.go
v2/container/marshal_test.go

Implement Unmarshal method on UsedSpaceAnnouncement v2 message. Implement
Marshal/Unmarshal methods on cross-version UsedSpaceAnnouncement type.

container: Implement marshalers on UsedSpaceAnnouncement

---

pkg/client/accounting.go
pkg/client/container.go
pkg/client/netmap.go
pkg/client/object.go
pkg/client/opts.go
pkg/client/session.go

Close #261 .
Remark about client cache from #261: i think `key` can be fully dropped from the client and provided for each request explicitly. Currently there is (?) possibility for bugs when some of the arguments are taken from client defaults. If cache from nspcc-dev/neofs-node is for connection reuse, key/token stuff should be provided on the other level. Thoughts?

Provide client key in call options

---

pkg/client/accounting.go
pkg/client/client.go
pkg/client/container.go
pkg/client/netmap.go
pkg/client/object.go
pkg/client/opts.go
pkg/client/session.go

Make it easier to test client API and mock specific methods. Can help to remove some wrappers from nspcc-dev/neofs-node (it can already be done, but changing tests is harder).
Also add comments on exported methods.
This interferes with #263, but not a lot.

pkg/client: Export `Client` interface instead of structure

---

pkg/client/reputation.go
pkg/reputation/peer.go
pkg/reputation/peer_test.go
pkg/reputation/test/generate.go
pkg/reputation/trust.go
pkg/reputation/trust_test.go
v2/reputation/convert.go
v2/reputation/grpc/service.go
v2/reputation/grpc/service.pb.go
v2/reputation/grpc/types.go
v2/reputation/grpc/types.pb.go
v2/reputation/json.go
v2/reputation/marshal.go
v2/reputation/message_test.go
v2/reputation/test/generate.go
v2/reputation/types.go
v2/rpc/reputation.go
v2/signature/sign.go

Compiled from https://github.com/nspcc-dev/neofs-api/pull/146.
Related to #265.

Support  reputation.SendIntermediateResult RPC

---

pkg/client/object.go

Allocate capacity instead of length of the slice to write the object payload
range since each chunk is written through `append`.

pkg/client: Fix payload slice allocation in Object Range method

---

go.mod
pkg/checksum.go
pkg/client/accounting.go
pkg/client/container.go
pkg/client/netmap.go
pkg/client/object.go
pkg/client/reputation.go
pkg/client/session.go
pkg/container/fmt.go
pkg/container/id.go
pkg/object/fmt.go
pkg/object/id.go
pkg/owner/id.go
pkg/owner/wallet.go
pkg/version.go
rpc/client/flows.go
rpc/message/test/message.go
util/proto/marshal_test.go
util/signature/util.go
v2/object/convert.go
v2/object/grpc/client.go
v2/session/convert.go
v2/session/grpc/client.go
v2/signature/sign.go

[#277] go.mod: remove `pkg/errors`

---

pkg/client/client.go
pkg/client/opts.go
rpc/client/connect.go
rpc/client/options.go

Relates to https://github.com/nspcc-dev/neofs-node/issues/455.
TLS configuration option was added to the client.
Deleted useless raw client initialization in `clientImpl`'s constructor.

Feature/add TLS options to client

---

pkg/owner/id.go
pkg/owner/id_test.go
pkg/owner/test/id.go
pkg/session/container.go
pkg/session/container_test.go
pkg/session/session.go
pkg/session/session_test.go
pkg/session/test/container.go
pkg/session/test/token.go

Implement session contexts

---

pkg/client/client.go
pkg/client/raw.go
rpc/client/conn.go
rpc/grpc/conn.go

Closes #196.
Minimum necessary connection control - closing (so `io.Closer`). For more flexible control of a particular type of connection, casters will be implemented in the future according to needs.

Connection readers on clients

---

pkg/client/opts.go
rpc/client/options.go
rpc/client/options_test.go

Add `WithURIAddress` option to client. It parses passed address with `url.ParseRequestURI` function and use(or not) TLS over grpc connection based on retrieved scheme( `grpc` or `grpcs`).
Related to https://github.com/nspcc-dev/neofs-node/issues/455.

Feature/Add `WithURIAddress` option

---

CHANGELOG.md
README.md
v2/session/grpc/types.pb.go

Merge after https://github.com/nspcc-dev/neofs-api/pull/159

Update *.pb.go files and changelog for v1.27.0 release

---

pkg/object/object.go

Add `MarshalHeaderJSON` method to `pkg/object`. Closes #300.

Feature/add `MarshalHeaderJSON` method

---

pkg/accounting/decimal_test.go
pkg/accounting/test/decimal.go
pkg/acl/eacl/table_test.go
pkg/acl/eacl/test/generate.go
pkg/audit/result_test.go
pkg/audit/test/generate.go
pkg/container/announcement_test.go
pkg/container/container_test.go
pkg/container/test/generate.go
pkg/netmap/test/generate.go
pkg/object/test/generate.go
pkg/storagegroup/storagegroup_test.go
pkg/storagegroup/test/generate.go
pkg/test/generate.go
pkg/token/bearer_test.go
pkg/token/test/generate.go

pkg: Implement generators for testing

---

v2/accounting/test/generate.go
v2/acl/test/generate.go
v2/audit/test/generate.go
v2/container/test/generate.go
v2/netmap/test/generate.go
v2/object/test/generate.go
v2/refs/test/generate.go
v2/reputation/test/generate.go
v2/session/test/generate.go
v2/storagegroup/test/generate.go
v2/tombstone/test/generate.go

Move all memory allocation and field settings in `GenerateTYPE(empty bool) *TYPE` functions behind `if !empty` check. Exceptions: meta fields such as signatures, hashes, headers, etc, since it seems that such fields are not going to be filled/edited manually in unit tests but at the same time obtaining "true" empty structures is equivalent to just `new(TYPE)`.
Related to #276.

Fix/Do not allocate memory if `empty`

---

pkg/client/object.go
pkg/client/object_test.go

Fix object stream-based io.Reader

---

pkg/acl/types.go

In the well-known BasicACL constants we need to set the always toggled bits for the system group. Otherwise it may be confusing for those who read the specification and try to match it with the reference implementation or the resulting BasicACL set in the container.

Fix well-known BasicACL constants to fit the spec

---

pkg/owner/wallet.go

The bug was detected after local updating of neo-go library which started to use `Curve` field in `PublicKey.Address` method.

Prevent potential NPE in NEO3WalletFromPublicKey

---

pkg/client/accounting.go
pkg/client/container.go
pkg/client/netmap.go
pkg/client/object.go
pkg/client/opts.go
pkg/client/reputation.go
pkg/client/response.go
pkg/client/session.go
v2/rpc/reputation.go

client: Response info callback

---

Makefile
prepare.sh

1. Use go install in `protoc` target.
`go get: installing executables with 'go get' in module mode is deprecated.`
2. Allow to have whitespaces in directories.
3. Fail early if cd target doesn't exist.

Fix directory handling in `prepare.sh`

---

netmap/attributes.go
netmap/attributes_test.go
refs/marshal.go
refs/types.go
refs/types_test.go

* Blocked by #355
* Closes #356
Example of `SubnetID` type can be used in #355.

Support node attributes related to subnets

---

Makefile

It caused an error in my case: 
```
go test: -i flag is deprecated
go test net: copying /home/kira/.cache/go-build/42/42a7dcda83d6782844dece1e4eb3e1447fa9792df66faa25dfd1f8dc8ef14c52-d: open /usr/lib/go/pkg/linux_amd64/net.a: permission denied
```
Signed-off-by: Angira Kekteeva <kira@nspcc.ru>

[#364] Makefile: Remove deprecated -i flag

---

prepare.sh
util/proto/test/test.proto

Return proto file for stable marshal tests

---

rpc/client/connect.go
rpc/client/options.go
rpc/grpc/init.go
rpc/grpc/options.go

Remote gRPC server may not return or accept data for a while. gRPC solves this issue with timeout in context. However, the context is used for entire gRPC method invocation. Unfortunately the duration of requests with streams can't be estimated easily.
To solve this issue we can specify timeouts for every message read and write. Single message has size limit so timeout can be related to that.

rpc/grpc: Perform read-write message operations with timeout 

---

status/details.go
status/grpc/types.pb.go
status/status.go
status/test/generate.go
status/types.go

I checked that method removal doesn't break the compatibility and decided to not mark it deprecated.

Support `WRONG_MAGIC_NUMBER` status

---

CHANGELOG.md

Release v2.12.2

---

util/proto/marshal.go
util/proto/marshal_test.go

util/proto: marshal repeated []byte fields correctly

---

.github/workflows/dco.yml

It's a single workflow for every repo, can't be better than that.

workflows: use newer, better DCO

---

acl/convert.go
acl/types.go
acl/types_test.go
object/convert_test.go
object/types.go

Make codegen from https://github.com/nspcc-dev/neofs-api/commit/541cd3cd8d030b5670e7e247122395dfabaadeac.

acl,object: Add new `MatchType` enum values after protocol extension
