nspcc-dev/neofs-api-go

accounting/service.pb.go, accounting/service.proto, accounting/withdraw.pb.go, accounting/withdraw.proto, bootstrap/service.pb.go, bootstrap/service.proto, container/service.pb.go, container/service.proto, container/types.pb.go, container/types.proto, docs/accounting.md, docs/bootstrap.md, docs/container.md, docs/object.md, docs/query.md, docs/refs.md, docs/session.md, object/service.pb.go, object/service.proto, object/types.pb.go, object/types.proto, query/types.pb.go, query/types.proto, refs/types.pb.go, refs/types.proto, session/service.pb.go, session/service.proto, session/types.pb.go, session/types.proto
- updated proto doc comments to satisfy go-doc comment
- added deprecation notice for epoch and ttl fields
- regenerated proto files
- regenerated proto documentation
fix #4
=> Update proto documentation

.github/workflows/go.yml, container/service.go, container/types.go, proto.go, session/types.go
=> Add ci GitHub actions

.github/workflows/go.yml
=> Add CODECOV_TOKEN

go.mod, go.sum, object/utils.go
- SendPutRequest unused and work not like expected
- MakePutRequestHeader should not set epoch / ttl
- remove unused internal functions and consts
=> Remove SendPutRequest and update MakePutRequestHeader

service/meta.go, service/meta_test.go
=> Process request ttl should not change status errors

service/epoch.go, service/meta.go
=> service: Renamed EpochRequest to EpochHeader and merged with MetaHeader

service/meta.go, service/meta_test.go
=> Get status error even if it is wrapped

go.mod, go.sum, object/utils.go, object/utils_test.go
- add ByteSize type + Stringer
- add test coverage
- cleanup modules
closes #22
=> service: get rid of bytefmt

Makefile, docs/state.md, state/service.go, state/service.pb.go, state/service.proto, state/service_test.go
- Refactoring Makefile
- Update documentation
- Update service.proto file and generate go-code
- Implement function to encode debug variables
- Add tests for EncodeVariables
=> Add method to state service to dump debug variables

state/service_test.go
- Add tests for EncodeConfig
- Add tests for EncodeMetrics and DecodeMetrics
=> Increase tests for state package

object/service.go, object/service_test.go
- cover good case (https://codecov.io/gh/nspcc-dev/neofs-api-go/commit/3d873d38bc4a15ea842204570bb39a0740a521b1)
- simplify logic
=> More test case for cid getter

Makefile, docs/state.md, state/service.pb.go, state/service.proto
The main objective of this method is to allow to control and manage the state of the node by its owner.
- if the user is not declared in the settings, the system returns an access error.
- if the new status is not defined or is not known, the system notifies about that.
- if the new status is known to the system, it will be applied and the node will change the current status.
=> Update to NeoFS API v0.7.1

session/alias.go, session/private.go, session/private_test.go, session/service.go, session/store.go, session/store_test.go, session/types.go
Summary:
- make private token to be an interface of data signer;
- replace session key generation from TokenStore instance to a separate function;
- refactor TokenStore to be key-value storage;
- improve file structure and documentation;
- remove no longer used types and errors.
Incoming changes:
- private token lifetime and garbage collecting of storage.
=> Session package refactoring

container/types.go, hash/hash.go, internal/proto.go, object/types.go, object/types_test.go, refs/address.go, refs/cid.go, refs/owner.go, refs/types_test.go, refs/uuid.go, service/verify.go
I propose to discuss this functionality because it is quite convenient and in demand in the code.
=> Implementing proto.Clone

v2/container/convert.go, v2/container/grpc/types.go, v2/container/types.go, v2/netmap/convert.go, v2/netmap/types.go, v2/service/convert.go, v2/service/service.go, v2/session/convert.go, v2/session/types.go
Adds uni-structures with gRPC converters for:
- `netmap.PlacementPolicy`;
- `container.Container`;
- `service.SessionToken`.
=> Implement some universal structures

v2/container/convert.go, v2/container/types.go
Implements uni-structures for requests and responses of `Container` service.
=> v2/container: Implement remaining uni-structures

util/proto/marshal.go, v2/accounting/accounting.go, v2/accounting/marshal.go, v2/accounting/marshal_test.go, v2/acl/marshal.go, v2/refs/marshal.go, v2/service/marshal.go, v2/storagegroup/marshal.go
This PR also contains extra proto heler for nesting structures. This helper reduces code of stable marshal and stable size functions.
=> Add stable marshal for accounting package

v2/accounting/accounting.go, v2/accounting/service.go, v2/container/service.go, v2/container/types.go, v2/session/service.go, v2/session/types.go
Define interfaces that reflect service (Accounting, Container, Session)
declarations in the API.
=> [#xx] v2: Define API service interfaces

pkg/object/id.go, pkg/object/id_test.go, pkg/object/object.go, pkg/object/raw.go
- Define `object.ID`;
- Define immutable `Object` and implement some useful methods (`ToV2`, `Verify`);
- Define mutable `RawObject` and implement setters on it;
- Implement `refs.Object` to `Object` converter.
=> Define Object types

pkg/checksum.go, pkg/checksum_test.go, pkg/client/accounting.go, pkg/client/client.go, pkg/client/container.go, pkg/client/object.go, pkg/client/opts.go, pkg/container/id.go, pkg/container/id_test.go, pkg/object/address.go, pkg/object/attribute.go, pkg/object/attribute_test.go, pkg/object/fmt.go, pkg/object/fmt_test.go, pkg/object/id.go, pkg/object/id_test.go, pkg/object/object.go, pkg/object/raw.go, pkg/object/raw_test.go, pkg/object/rw.go, pkg/owner/id.go, pkg/owner/id_test.go, pkg/signature.go, pkg/version.go, pkg/version_test.go
- Add `Version`, `Signature` and `Checksum` types;
- Refactor reference types in SDK;
- Refactor `Object` and `RawObject`;
- Implement functions for forming the structure `RawObject` and checking the structure of `Object`.
=> Implement Object structure and useful functions in SDK

pkg/client/object.go
=> sdk/client: Fix object operations

pkg/acl/eacl/enums.go, pkg/acl/eacl/enums_test.go, pkg/acl/eacl/filter.go, pkg/acl/eacl/filter_test.go, pkg/acl/eacl/record.go, pkg/acl/eacl/record_test.go, pkg/acl/eacl/table.go, pkg/acl/eacl/table_test.go, pkg/acl/eacl/target.go, pkg/acl/eacl/target_test.go, pkg/client/container.go, v2/acl/convert.go, v2/acl/marshal.go, v2/acl/marshal_test.go, v2/acl/types.go, v2/container/marshal_test.go, v2/object/marshal_test.go, v2/session/marshal_test.go
=> Extended ACL support

pkg/client/object.go, pkg/client/opts.go, pkg/client/session.go, pkg/token/session.go
Sort of draft, will be updated after v2.0.0-rc-1.
=> Session token support in SDK Object RPC calls

pkg/container/container.go, pkg/netmap/node_info.go, pkg/netmap/node_info_test.go, pkg/object/address.go, pkg/object/address_test.go
- add `container.ID` calculating func;
- add network address getter to SDK `netmap.Node` type;
- add getters and setters to SDK `object.Address` type.
=> Implement some needed methods and functions

pkg/client/opts.go, pkg/token/bearer.go
Merge after #139 
Sort of draft, that will be updated after v2.0.0-rc-1.
=> Bearer token support in SDK Object RPC calls

pkg/client/object.go
=> sdk/client: Set object identifier in Head result

pkg/object/fmt.go
=> sdk/object: Detach header verification functions

internal/error.go, pkg/container/id.go, pkg/container/id_test.go, pkg/object/address.go, pkg/object/address_test.go, pkg/object/id.go, pkg/object/id_test.go, pkg/owner/id.go, pkg/owner/id_test.go, pkg/owner/wallet.go
Implement Stringer interface and Parse method for well-known types
=> [#147] Implement Stringer interface and Parse method for common types

pkg/container/wellknown_attributes.go, pkg/object/wellknown_attributes.go, v2/container/attributes.go, v2/object/attributes.go
=> Define well-known container and object attributes

pkg/version.go, pkg/version_test.go
Implement function that checks the compatibility of the specified version with the current NeoFS revision.
=> sdk: Implement IsSupportedVersion function

pkg/client/netmap.go
Implement `Epoch` method on Client that receives epoch number through `Netmap.LocalNodeInfo` call.
=> sdk/client: Implement Epoch method

pkg/client/object.go, pkg/object/error.go, pkg/object/error_test.go
=> Split Info as a pointer

CHANGELOG.md, README.md
=> Update changelog and readme for v1.21.0

pkg/object/search.go, pkg/object/search_test.go, pkg/object/type.go, pkg/object/type_test.go, v2/object/string.go
- implement string encoder/decoder for object `Type`;
- implement method to add search filter by object type.
=> Implement stringer for object Type

CHANGELOG.md, v2/acl/grpc/types.pb.go, v2/container/grpc/types.pb.go, v2/netmap/grpc/types.pb.go, v2/object/grpc/types.pb.go, v2/refs/grpc/types.pb.go
- recompile protobuf files
- update changelog
=> Prepare to release v1.21.1

v2/session/grpc/service.pb.go, v2/session/grpc/types.pb.go, v2/session/xheaders.go
=> v2/session: Define keys of the well-known X-headers

CHANGELOG.md
=> Update changelog for release v1.22.1

pkg/client/object.go
Object payload transferred in chunks. Size of the chunks may be limited by transport protocols. To split it we use `io.CopyBuffer` with pre-allocated buffer size of one chunk. However this function may ignore buffer if reader or writer implements `WriteTo` or `ReadFrom` methods. Unfortunately `bytes.Reader` implements `WriteTo` function.
To fix this we wrap reader so wrapper implements only `io.Reader` interface.
Related to github.com/nspcc-dev/neofs-node/issues/338
=> Use io.Reader wrapper at object put in pkg client

pkg/netmap/policy_test.go, pkg/netmap/selector.go, pkg/netmap/selector_test.go
Implement 1b from comment #248 .
=> [#248] netmap: fulfill backup factor for default attribute

pkg/netmap/filter.go, pkg/netmap/node_info.go, pkg/netmap/selector_test.go, pkg/object/search.go, pkg/object/search_test.go, v2/netmap/grpc/types.pb.go, v2/object/json.go, v2/object/json_test.go
=> Implement JSON encoding of object search filters

CHANGELOG.md, README.md
=> Update changelog and readme for release v1.23.0

pkg/acl/eacl/filter.go, pkg/acl/eacl/filter_test.go, pkg/acl/eacl/record.go, pkg/acl/eacl/record_test.go, pkg/acl/eacl/table.go, pkg/acl/eacl/table_test.go, pkg/acl/eacl/target.go, pkg/acl/eacl/target_test.go
=> Fix conversions of eACL entities

pkg/session/session.go, pkg/session/session_test.go, pkg/session/test/token.go
=> Add session.Token lifetime API

rpc/grpc/util.go
=> grpc: Fix the format of full method names

pkg/client/object.go
Define `ReaderHandler` type. Add `GetObjectParams.WithPayloadReaderHandler`
method which accepts `ReaderHandler`. The handler is called right after
header receipt in `Client.GetObject`. After the handler is called,
`GetObject` returns object header immediately.
Closes #313.
=> client/object: Add payload-handling parameter to GetObjectParams

pkg/acl/eacl/enums.go, pkg/acl/eacl/enums_test.go, pkg/checksum.go, pkg/checksum_test.go, pkg/netmap/clause.go, pkg/netmap/clause_test.go, pkg/netmap/helper_test.go, pkg/netmap/node_info.go, pkg/netmap/node_info_test.go, pkg/netmap/operation.go, pkg/netmap/operation_test.go, pkg/object/search.go, pkg/object/search_test.go, pkg/object/type.go, pkg/object/type_test.go, v2/acl/grpc/types.go, v2/acl/string.go, v2/netmap/grpc/types.go, v2/netmap/string.go, v2/object/grpc/types.go, v2/object/string.go, v2/refs/grpc/types.go, v2/refs/string.go, v2/session/grpc/types.go, v2/session/string.go
Closes #310.
Suggestions for more nifty parsers of gRPC enums are welcome.
=> Implement string converters for enumerations

CHANGELOG.md, pkg/client/object.go
=> pkg/client: Fix session token corruption

pkg/acl/types.go
=> Fix well-known BasicACL constants to fit the spec

pkg/acl/types.go
=> acl: Define public-append rule

README.md
=> [#368] README.md: change desctiption and link to SDK

object/attributes.go, object/attributes_test.go, object/bench_test.go, object/convert.go, object/marshal.go, object/test/generate.go, object/types.go
=> Remove pointer from `object.Attribute` slice

util/protogen/main.go
This version was used to implement stable marshalers for the tree service.
=> Support latest API in protoc plugin

util/protogen/main.go
=> protogen: uncomment control service line

Makefile
Signed-off-by: anikeev-yadro <a.anikeev@yadro.com>
=> [#411] Filter version tags for version calculation

CHANGELOG.md
=> Release v2.14.0

netmap/convert.go
Likely this better stay as is for compatibility.
=> netmap: fix linter warning

go.mod, go.sum, signature/sign_test.go, util/signature/data.go, util/signature/options.go, util/signature/walletconnect/sign.go
Refs. https://github.com/nspcc-dev/neofs-crypto/pull/22
Refs. https://github.com/nspcc-dev/rfc6979/issues/6
=> Drop neofs-crypto dependency
